from datetime import datetime, timedelta, timezone

import jwt
import bcrypt
from fastapi import HTTPException, status

from portal.config import (
    PORTAL_JWT_SECRET,
    PORTAL_JWT_ALGORITHM,
    PORTAL_JWT_EXPIRE_MINUTES,
    MOODLE_PORTAL_JWT_SECRET,
)


# ── Password hashing ──

def hash_password(password: str) -> str:
    pwd_bytes = password.encode('utf-8')
    salt = bcrypt.gensalt()
    hashed_password = bcrypt.hashpw(pwd_bytes, salt)
    return hashed_password.decode('utf-8')


def verify_password(plain_password: str, hashed_password: str) -> bool:
    password_byte_enc = plain_password.encode('utf-8')
    hashed_password_byte_enc = hashed_password.encode('utf-8')
    return bcrypt.checkpw(password_byte_enc, hashed_password_byte_enc)


# ── Portal session JWT ──

def create_portal_jwt(student_id: int, email: str) -> str:
    """Create a portal session JWT for an authenticated student."""
    now = datetime.now(timezone.utc)
    payload = {
        "sub": str(student_id),
        "email": email,
        "iat": now,
        "exp": now + timedelta(minutes=PORTAL_JWT_EXPIRE_MINUTES),
    }
    return jwt.encode(payload, PORTAL_JWT_SECRET, algorithm=PORTAL_JWT_ALGORITHM)


def decode_portal_jwt(token: str) -> dict:
    """Decode and validate a portal session JWT. Raises HTTPException on failure."""
    try:
        payload = jwt.decode(token, PORTAL_JWT_SECRET, algorithms=[PORTAL_JWT_ALGORITHM])
        if "sub" not in payload:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Token invalido: campo 'sub' ausente",
            )
        return payload
    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token expirado",
        )
    except jwt.InvalidTokenError as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Token invalido: {e}",
        )


# ── Moodle redirect JWT ──

def validate_moodle_token(token: str) -> dict:
    """Validate a JWT generated by the Moodle plugin for the portal redirect flow.

    Expected payload fields: moodle_user_id, email, full_name, iat, exp.
    """
    try:
        payload = jwt.decode(token, MOODLE_PORTAL_JWT_SECRET, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token de Moodle expirado. Vuelva a acceder desde Moodle.",
        )
    except jwt.InvalidTokenError as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Token de Moodle invalido: {e}",
        )

    required_fields = ("moodle_user_id", "email", "full_name")
    missing = [f for f in required_fields if f not in payload]
    if missing:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Token de Moodle incompleto: faltan {', '.join(missing)}",
        )

    return payload
