from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from portal.auth import (
    create_portal_jwt,
    validate_moodle_token,
    hash_password,
    verify_password,
)
from portal.dependencies import get_portal_db, get_current_user
from portal.models import PortalStudent
from portal.schemas import (
    AuthResponse,
    LoginRequest,
    MoodleCallbackRequest,
    SetPasswordRequest,
    StudentInfo,
)

auth_router = APIRouter(prefix="/auth", tags=["Portal Auth"])


@auth_router.post("/moodle-callback", response_model=AuthResponse)
def moodle_callback(request: MoodleCallbackRequest, db: Session = Depends(get_portal_db)):
    """Authenticate a student via a JWT generated by the Moodle plugin.

    Creates a portal account on first access; updates profile on subsequent ones.
    """
    payload = validate_moodle_token(request.token)

    moodle_user_id = int(payload["moodle_user_id"])
    email = payload["email"]
    full_name = payload["full_name"]

    student = (
        db.query(PortalStudent)
        .filter(PortalStudent.moodle_user_id == moodle_user_id)
        .first()
    )

    now = datetime.now(timezone.utc)

    if student:
        student.email = email
        student.full_name = full_name
        student.last_login_at = now
    else:
        student = PortalStudent(
            moodle_user_id=moodle_user_id,
            email=email,
            full_name=full_name,
            last_login_at=now,
        )
        db.add(student)

    db.commit()
    db.refresh(student)

    access_token = create_portal_jwt(student.id, student.email)

    return AuthResponse(
        access_token=access_token,
        student=StudentInfo(
            id=student.id,
            moodle_user_id=student.moodle_user_id,
            email=student.email,
            full_name=student.full_name,
            has_password=student.password_hash is not None,
            created_at=student.created_at,
        ),
    )


@auth_router.post("/login", response_model=AuthResponse)
def login(request: LoginRequest, db: Session = Depends(get_portal_db)):
    """Authenticate with email and password (only for students who have set a password)."""
    student = db.query(PortalStudent).filter(PortalStudent.email == request.email).first()

    if not student or not student.is_active:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Credenciales invalidas",
        )

    if not student.password_hash:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Esta cuenta no tiene contrasena configurada. Acceda primero desde Moodle y configure una contrasena en el portal.",
        )

    if not verify_password(request.password, student.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Credenciales invalidas",
        )

    student.last_login_at = datetime.now(timezone.utc)
    db.commit()
    db.refresh(student)

    access_token = create_portal_jwt(student.id, student.email)

    return AuthResponse(
        access_token=access_token,
        student=StudentInfo(
            id=student.id,
            moodle_user_id=student.moodle_user_id,
            email=student.email,
            full_name=student.full_name,
            has_password=True,
            created_at=student.created_at,
        ),
    )


@auth_router.get("/me", response_model=StudentInfo)
def get_me(current_user: PortalStudent = Depends(get_current_user)):
    """Return profile information for the currently authenticated student."""
    return StudentInfo(
        id=current_user.id,
        moodle_user_id=current_user.moodle_user_id,
        email=current_user.email,
        full_name=current_user.full_name,
        has_password=current_user.password_hash is not None,
        created_at=current_user.created_at,
    )


@auth_router.post("/set-password", response_model=StudentInfo)
def set_password(
    request: SetPasswordRequest,
    current_user: PortalStudent = Depends(get_current_user),
    db: Session = Depends(get_portal_db),
):
    """Set or update the portal password for the authenticated student.

    This enables direct email+password login without needing to go through Moodle.
    """
    current_user.password_hash = hash_password(request.password)
    db.commit()
    db.refresh(current_user)

    return StudentInfo(
        id=current_user.id,
        moodle_user_id=current_user.moodle_user_id,
        email=current_user.email,
        full_name=current_user.full_name,
        has_password=True,
        created_at=current_user.created_at,
    )
