from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, EmailStr, Field, field_validator

from blockchain.base import AnchorStatus


# ── Request Models ──

class MoodleCallbackRequest(BaseModel):
    token: str = Field(..., min_length=10, description="JWT token generated by Moodle plugin")


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=1)


class SetPasswordRequest(BaseModel):
    password: str = Field(..., min_length=8, max_length=128, description="Mínimo 8 caracteres, al menos 1 mayúscula y 1 número.")

    @field_validator('password')
    @classmethod
    def validate_password_complexity(cls, v: str) -> str:
        if not any(char.isupper() for char in v):
            raise ValueError('La contraseña debe contener al menos una letra mayúscula')
        if not any(char.isdigit() for char in v):
            raise ValueError('La contraseña debe contener al menos un número')
        return v


# ── Response Models ──

class StudentInfo(BaseModel):
    id: int
    moodle_user_id: int
    email: str
    full_name: str
    has_password: bool
    created_at: datetime

    class Config:
        from_attributes = True


class AuthResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    student: StudentInfo


class BlockchainEvidence(BaseModel):
    """Public, verifier-facing snapshot of on-ledger credential evidence.

    Fields beyond ``network`` and ``status`` are populated progressively
    as the anchoring pipeline matures; clients must drive their UI from
    ``status`` rather than from the presence of optional fields.
    """

    network: str
    status: AnchorStatus
    issuer_did: Optional[str] = None
    schema_id: Optional[str] = None
    cred_def_id: Optional[str] = None
    rev_reg_id: Optional[str] = None
    cred_rev_id: Optional[str] = None
    txn_id: Optional[str] = None
    seq_no: Optional[int] = None
    ledger_timestamp: Optional[str] = None
    explorer_url: Optional[str] = None


class CredentialSummary(BaseModel):
    id: int
    course_name: str
    course_id: int
    status: str
    completion_date: Optional[str] = None
    credential_hash: Optional[str] = None
    created_at: Optional[str] = None


class CredentialDetail(CredentialSummary):
    student_name: Optional[str] = None
    student_email: Optional[str] = None
    grade: Optional[str] = None
    invitation_url: Optional[str] = None
    qr_code_base64: Optional[str] = None
    blockchain: Optional[BlockchainEvidence] = None
    claimed_at: Optional[str] = None


class StatsResponse(BaseModel):
    total_credentials: int = 0
    pending: int = 0
    issued: int = 0
    claimed: int = 0


class PublicVerificationResponse(BaseModel):
    valid: bool
    credential_hash: str
    student_name: Optional[str] = None
    course_name: Optional[str] = None
    completion_date: Optional[str] = None
    issuer: Optional[str] = None
    blockchain: Optional[BlockchainEvidence] = None
