from datetime import datetime
from typing import Optional

from pydantic import BaseModel, EmailStr, Field


# ── Request Models ──

class MoodleCallbackRequest(BaseModel):
    token: str = Field(..., min_length=10, description="JWT token generated by Moodle plugin")


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=1)


class SetPasswordRequest(BaseModel):
    password: str = Field(..., min_length=8, max_length=128)


# ── Response Models ──

class StudentInfo(BaseModel):
    id: int
    moodle_user_id: int
    email: str
    full_name: str
    has_password: bool
    created_at: datetime

    class Config:
        from_attributes = True


class AuthResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    student: StudentInfo


class CredentialSummary(BaseModel):
    id: int
    course_name: str
    course_id: int
    status: str
    completion_date: Optional[str] = None
    fabric_hash: Optional[str] = None
    created_at: Optional[str] = None


class CredentialDetail(CredentialSummary):
    student_name: Optional[str] = None
    student_email: Optional[str] = None
    grade: Optional[str] = None
    invitation_url: Optional[str] = None
    qr_code_base64: Optional[str] = None
    fabric_verified: Optional[bool] = None
    fabric_asset_id: Optional[str] = None
    claimed_at: Optional[str] = None


class StatsResponse(BaseModel):
    total_credentials: int = 0
    pending: int = 0
    issued: int = 0
    claimed: int = 0


class PublicVerificationResponse(BaseModel):
    valid: bool
    credential_hash: str
    student_name: Optional[str] = None
    course_name: Optional[str] = None
    completion_date: Optional[str] = None
    issuer: Optional[str] = None
    blockchain_confirmed: bool = False
