from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, EmailStr, Field, field_validator

from blockchain.base import AnchorStatus


# ── Request Models ──

class MoodleCallbackRequest(BaseModel):
    token: str = Field(..., min_length=10, description="JWT token generated by Moodle plugin")


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=1)


class SetPasswordRequest(BaseModel):
    password: str = Field(..., min_length=8, max_length=128, description="Mínimo 8 caracteres, al menos 1 mayúscula y 1 número.")

    @field_validator('password')
    @classmethod
    def validate_password_complexity(cls, v: str) -> str:
        if not any(char.isupper() for char in v):
            raise ValueError('La contraseña debe contener al menos una letra mayúscula')
        if not any(char.isdigit() for char in v):
            raise ValueError('La contraseña debe contener al menos un número')
        return v


# ── Response Models ──

class StudentInfo(BaseModel):
    id: int
    moodle_user_id: int
    email: str
    full_name: str
    has_password: bool
    created_at: datetime

    class Config:
        from_attributes = True


class AuthResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    student: StudentInfo


class BlockchainEvidence(BaseModel):
    """Public, verifier-facing snapshot of on-ledger credential evidence.

    Fields beyond ``network`` and ``status`` are populated progressively
    as the anchoring pipeline matures; clients must drive their UI from
    ``status`` rather than from the presence of optional fields.
    """

    network: str
    status: AnchorStatus
    issuer_did: Optional[str] = None
    schema_id: Optional[str] = None
    cred_def_id: Optional[str] = None
    rev_reg_id: Optional[str] = None
    cred_rev_id: Optional[str] = None
    txn_id: Optional[str] = None
    seq_no: Optional[int] = None
    ledger_timestamp: Optional[str] = None
    explorer_url: Optional[str] = None


class CredentialSummary(BaseModel):
    id: int
    course_name: str
    course_id: int
    status: str
    completion_date: Optional[str] = None
    credential_hash: Optional[str] = None
    created_at: Optional[str] = None


class CredentialDetail(CredentialSummary):
    student_name: Optional[str] = None
    student_email: Optional[str] = None
    grade: Optional[str] = None
    invitation_url: Optional[str] = None
    qr_code_base64: Optional[str] = None
    blockchain: Optional[BlockchainEvidence] = None
    claimed_at: Optional[str] = None


class StatsResponse(BaseModel):
    total_credentials: int = 0
    pending: int = 0
    issued: int = 0
    claimed: int = 0


class PublicVerificationResponse(BaseModel):
    valid: bool
    credential_hash: str
    student_name: Optional[str] = None
    course_name: Optional[str] = None
    completion_date: Optional[str] = None
    issuer: Optional[str] = None
    blockchain: Optional[BlockchainEvidence] = None


# ── Blockchain registry (public + admin) ──

class LedgerArtifactView(BaseModel):
    """Verifier-facing view of a ledger artifact (schema, cred_def, rev_reg_def)."""

    kind: str
    artifact_id: str
    name: Optional[str] = None
    version: Optional[str] = None
    tag: Optional[str] = None
    issuer_did: Optional[str] = None
    schema_id: Optional[str] = None
    supports_revocation: bool = False
    seq_no: Optional[int] = None
    explorer_url: Optional[str] = None


class RevRegView(BaseModel):
    """Public view of the institutional revocation registry."""

    kind: str = "rev_reg_def"
    rev_reg_id: str
    cred_def_id: Optional[str] = None
    issuer_did: Optional[str] = None
    tag: Optional[str] = None
    max_cred_num: Optional[int] = None
    issuance_type: Optional[str] = None
    tails_location: Optional[str] = None
    explorer_url: Optional[str] = None


class BlockchainRegistryResponse(BaseModel):
    """Snapshot of the institutional registry anchored on the ledger."""

    network: str
    issuer_did: Optional[str] = None
    explorer_url: Optional[str] = None
    schema: Optional[LedgerArtifactView] = None
    cred_def: Optional[LedgerArtifactView] = None
    rev_reg: Optional[RevRegView] = None
    total_anchored_credentials: int = 0


class BootstrapArtifactReport(BaseModel):
    """Outcome for a single artifact processed by the bootstrap."""

    kind: str
    artifact_id: str
    outcome: str
    seq_no: Optional[int] = None


class BootstrapResponse(BaseModel):
    """Response body for ``POST /api/admin/blockchain/bootstrap``."""

    issuer_did: str
    network: str
    schema_id: str
    cred_def_id: str
    supports_revocation: bool
    schema: BootstrapArtifactReport
    cred_def: BootstrapArtifactReport
    rev_reg: Optional[BootstrapArtifactReport] = None
    rev_reg_id: Optional[str] = None
    rev_reg_max_cred_num: Optional[int] = None
    rev_reg_issuance_type: Optional[str] = None
